version: '3.3'

services:
    node-app:
        build: ./app
        environment:
            - DATABASE_HOST=db
        depends_on:
            - db
        restart: always
        ports:
            - "8080:8080"
    db:
        image: mysql:5.7
        build: ./mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=school
        restart: always
        ports:
            - "3306:3306"